### ISSUE TITLE
Mod deployment (v1)

### ISSUE THREAD

**Issue by malgreen** [Malgreen/NexNux#8]
'Deployment' of mods means that we link each file in our chosen 'mods' directory to our 'deploy' directory.
There should be a cache of what was in the 'deploy' directory before anything was done to it, which would allow for this type of deployment:

1. Pre-deploy cache is restored to 'deploy' directory, by: 
*a*. Removing all links whose path is in the 'DeployedFiles.json'
*b*. Moving every file that is in the 'deploy cache' to the 'deploy' directory
2. Each file for each enabled mod is linked to the 'deploy' directory, starting with index 0
*a*. If a file with that name already exist in the 'deploy' directory, and isn't in the new 'deploy cache', add it to the new 'deploy cache'
*b*. If file link is succesful, add its path to a .json file by writing a List<> of files to a 'DeployedFiles.json' (existing filenames are replaced)
3. Done

**Comment by Malgreen** [comment]
First version of mod deployment implemented in 5191b01bde167ed7b304ca48ed92cda7f2b6d500
